### PR TITLE
Package up skiplink

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- `npm run package` to package up Skiplink component - forgot to do in previous PR.

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama I think I'm going to merge this in, since there's nothing new - I forgot to package up the Skiplink component so this is just me running `npm run package` on main.

**Comment by yvonnetangsu** [comment]
🤠  pew pew

**Comment by sherakama** [comment]
We should add a github workflow to compile and commit for us so we don't forget again...

**Comment by yvonnetangsu** [comment]
> We should add a github workflow to compile and commit for us so we don't forget again...

That's a good idea. I'll look into it next week. Want to get my tickets in good shape first before leaving for long weekend.

**Pull request merged**
