### PR TITLE
ADAPT-000: Automagically run tests

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

### CODE REVIEW

**Comment by jbickar** [comment]
@jenbreese and @katrialesser I think this is where they are adding Jest tests.

(Surely, you jest.)

**Comment by sherakama** [comment]
Just getting started. Nothing really to see yet.

**Comment by sherakama** [comment]
@yvonnetangsu, this adds a workflow item to automatically run the jest tests so we can see them pass/fail in github instead of worrying about them running in netlify.

**Comment by jbickar** [comment]
> Just getting started. Nothing really to see yet.

Surely, you missed a golden opportunity to make an _Airplane!_ reference.

**Review by yvonnetangsu — APPROVED** [review]
Seems to work - approve!

**Pull request merged**
