### PR TITLE
ADAPT-3109 Add CTA link, CTA button, and button variants for form elements

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Add CTA link, CTA button, and button variants for form elements

# Needed By (Date)
- tbd

# Urgency
- medium/low

# Steps to Test

1. Pull this branch
2. Review locally at 
- Cta Link: `/story/simple-cta-link--default&args=color:green`
- Cta Button: `/story/simple-cta-link-button--primary`
- Button: `/story/simple-button--primary`

Or on Netlify
- [Cta Link](https://deploy-preview-72--decanter-react.netlify.app/?path=/story/simple-cta-link--form)
- [Cta Button](https://deploy-preview-72--decanter-react.netlify.app/?path=/story/simple-cta-link-button--primary)
- [Button](https://deploy-preview-72--decanter-react.netlify.app/?path=/story/simple-button--primary)

3. Compare the Cta Link Green variant and Cta Button/Button Primary and Secondary variant to [Figma Mocks](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=9799%3A127).

# Affected Projects or Products
- DERF
- MyAccount

# Associated Issues and/or People
- [ADAPT-3109](https://stanfordits.atlassian.net/browse/ADAPT-3109)
- [ADAPT-3098](https://stanfordits.atlassian.net/browse/ADAPT-3098)
- [ADAPT-3099](https://stanfordits.atlassian.net/browse/ADAPT-3099)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by yvonnetangsu — CHANGES_REQUESTED** [review]
Thanks for the work, @rebeccahongsf! These are looking really good. A few things

- Since these are not replacing the original solid/outline (red) buttons, could we label the form variants with "Form" in them so people know that they're intended for form use only. Eg, our current line up would become "Solid, Outline, Form Primary, Form Secondary, Ghost....."
- Form CTA Link looks great. Please add a story to use the form green variant and label it Form CTA Link 😄 
- Secondary button hover state needs some tweak
Screen Shot 2021-09-21 at 9 40 53 AM
- This is from Figma comparison - looks like all the form buttons need a shadow on hover, and they need a different active: background color compared to the hover/focus one.

**Comment by yvonnetangsu** [comment]
@rebeccahongsf Thank you for the changes! A few more:

- The buttons have "pressed" states in Figma, which means we're going to need some `active:` TW styles on top of the hover and focus we have. For example, for the blue primary form button, for the "pressed" state, the bg color is lighter than the :hover or :focus 😄 
Screen Shot 2021-09-21 at 1 09 41 PM
- Looks like for the primary form buttons, on hover/focus, there is no underline in Figma - please double check with Kerri
- Please add support for  disabled form buttons. Currently if I toggled on the isDisabled boolean
Screen Shot 2021-09-21 at 1 02 29 PM

Thank you for your patience and good work 🙏🏼 😄 !

**Comment by rebeccahongsf** [comment]
I've adjusted the buttons to include the default disable styles and added the Lagunita primary and secondary variants. 

Should we roll up the [File Button styles](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=9799%3A127) into this PR as well? I imagine we'll need to add an icon align left/right option/lever? 🤔 Or should this be a new component (e.g. FileButton)?

**Comment by yvonnetangsu** [comment]
> I've adjusted the buttons to include the default disable styles and added the Lagunita primary and secondary variants.
> 
> Should we roll up the [File Button styles](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=9799%3A127) into this PR as well? I imagine we'll need to add an icon align left/right option/lever? 🤔 Or should this be a new component (e.g. FileButton)?

So many buttons 😂  Thanks for the changes - I'll check them out later. As for the file button, let's do that in another PR since you're working on the hero icon refactor. We'll likely want to add a prop to have an option to move the icon to a leading position.

**Comment by rebeccahongsf** [comment]
> > I've adjusted the buttons to include the default disable styles and added the Lagunita primary and secondary variants.
> > Should we roll up the [File Button styles](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=9799%3A127) into this PR as well? I imagine we'll need to add an icon align left/right option/lever? 🤔 Or should this be a new component (e.g. FileButton)?
> 
> So many buttons 😂 Thanks for the changes - I'll check them out later. As for the file button, let's do that in another PR since you're working on the hero icon refactor. We'll likely want to add a prop to have an option to move the icon to a leading position.

Thanks Yvonne! 😄 I've created [ADAPT-3762](https://stanfordits.atlassian.net/browse/ADAPT-3762) to add the File Button variation once the Hero Icon changes have been implemented.

**Comment by yvonnetangsu** [comment]
@rebeccahongsf I'm curious about the border thickness change which results in the button size change. I kind of expect the button to stay the same size (so no shifting) when being clicked - perhaps something to check with our design team 😄

**Comment by yvonnetangsu** [comment]
@rebeccahongsf Try the ring utility, that might solve the shift in button position on click/hover
It uses box shadow to create the ring, here it says it works in combination with TW's regular drop shadow also.
https://tailwindcss.com/docs/ring-width

**Comment by yvonnetangsu** [comment]
@rebeccahongsf I'm glad the ring utility works. I feel like we need to get some clarification from the design team for the buttons. For example, I'm seeing that in Figma, the lagunita primary has different focus ring thickness compared to the blue primary form buttons, but I'm not sure that's intentional.  So let's do a 10 minute huddle next week and sort this out. Looking really great though 😄

**Review by yvonnetangsu — APPROVED** [review]
Thank you for all the revisions! 😄  GTG for me. We can add a ticket to clean up Proptypes for all existing components (including removing the refs that aren't functioning) later as @mattanglin has suggested in another PR.

**Comment by sherakama** [comment]
@rebeccahongsf This is now on hold. Please wait until further notice to where this work is going. We are going to be retiring this project and moving the work directly into projects.

**Pull request merged**
