### PR TITLE
ADAPT-000: Remove div and setdanger in alert component story.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Cleans up the alert story by removing the setdanger approach. 

# Needed By (Date)
- Whenver

# Urgency
- None

# Steps to Test

1. Review preview build

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by yvonnetangsu — APPROVED** [review]
Looks good to me. GTG. Looks like eslint complains but pre-approving in case you want to fix it.

**Comment by sherakama** [comment]
What do you do about the linter complaining about `href="#"` in these? Shall we just ignore that rule here?

**Comment by sherakama** [comment]
I went ahead and disabled the empty anchor check for this linter.

**Comment by yvonnetangsu** [comment]
> What do you do about the linter complaining about `href="#"` in these? Shall we just ignore that rule here?

Oh thanks, you disabled the checker. Was going to say I'm fine with ignoring it 😄

**Pull request merged**
