### PR TITLE
ADAPT-000: NPM Package Version Updates

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Updates some outdated package files.

# Needed By (Date)
- Whenever

# Urgency
- N/A

### CODE REVIEW

**Comment by sherakama** [comment]
Has the code from https://github.com/SU-SWS/decanter-react/pull/53 in here as well.

**Review by yvonnetangsu — APPROVED** [review]
Looks good to me! I merged the poster fix in and looks like there's a merge conflict with package-lock.json now. Preapproving.

**Review by rebeccahongsf — APPROVED** [review]
LGTM 🥳  Thanks Shea!

**Comment by sherakama** [comment]
I'm going to publish with an alpha release as I am not 100% sure the loose setting won't bork something.

**Pull request merged**
