### PR TITLE
ADAPT-2565

### PR DESCRIPTION
**Pull request by romakravchuk**
# READY FOR REVIEW/NOT READY
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Needed By (Date)
- When does this need to be merged by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by romakravchuk** [comment]
Hey @sherakama added styles as css file, tried to add like css module but to do that we need to configure storybook postcss addon in config file(main.js). So i make it simple and just import css file directly to js file

**Comment by sherakama** [comment]
@romakravchuk I think I may have lead you astray. Please move this work directly into the saa_alumni repo.

**Review by sherakama — CHANGES_REQUESTED** [review]
Please move to ~https://github.com/SU-SWS/saa_alumni~ https://github.com/SU-SWS/ood_online_giving

**Comment by romakravchuk** [comment]
oh, and to online_giving as well??  i need this changes there also

**Comment by sherakama** [comment]
> @sherakama oh, and to online_giving as well?? i need this changes there also

My mistake again. Just the online giving site. Not the SAA Alumni site at this time. Thanks for your patience.

**Comment by sherakama** [comment]
> no worries, 😉
> i have [task](https://stanfordits.atlassian.net/browse/ADAPT-2066) to build the alert for alumni, so i should ignore this changes for alumni

Let me check on that. I'm now not sure if the link styles are different or not on those two sites.

**Comment by yvonnetangsu** [comment]
It might be slightly easier on SAA Alumni site, since we have actually have TW installed there with a custom tailwind.config.js. We likely would need custom TW utilities/components to change the link background color in the WYSIWYG text, but probably no need for CSS modules.

**Comment by sherakama** [comment]
Ok, I got clarity from our UX team, in that yes, we do want these changes in this package. Let's noodle on this a bit about the approach because this is definitely a gap in TailwindCSS's approach to styling. Please continue with the implementation of the banners for the two sites minus this link hover state.

**Comment by sherakama** [comment]
@yvonnetangsu & @romakravchuk 

Ok, after deliberation on this we are going to go full circle. I'd like this moved back into each of the two other projects. I'd rather not introduce css modules to this library at this point as that will assume that the consumer has something like webpack with a css-loader to handle it. Please close this PR and move the work into each of the other two projects (SAA Alumni and OOD Online Giving). We will create a ticket to revisit this issue in Decanter-React later.

**Comment by yvonnetangsu** [comment]
@sherakama Sounds good to me!

**Pull request closed without merging**
